### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by bspringston** [irazasyed/jwt-auth-guard#11]
composer require irazasyed/jwt-auth-guard on my end returns:

  [InvalidArgumentException]  
  Could not find package irazasyed/jwt-auth-guard at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by irazasyed** [comment]
I didn't tag the package. Let me just release the first version since a lot of people have this issue.

I'm releasing without extensive testing though.

**Comment by irazasyed** [comment]
Done. It should work now!

**Comment by irazasyed** [comment]
Please report any bugs you come across or open a PR if you already have a fix. Thanks!

**Comment by bspringston** [comment]
The develop branch of tymondesigns/jwt-auth has JWT.php but the master branch does not.  This is causing a problem with:

use Tymon\JWTAuth\JWT in your JWTAuthGuard and is most likely the cause of this error i’m getting:

ReflectionException in Container.php line 738 <>:
Class tymon.jwt does not exist

Best,

Robert M. Springston
CEO and Co-Founder
Quipley, Inc.
333 City Boulevard West
17th Floor
Orange, CA  92868

Phone: 714.937.2010
Mobile: 310.359.3816 | Email: bspringston@quipley.com mailto:bspringston@gmail.com
http://www.quipley.com http://www.quipley/

This item/document/material contains CONFIDENTIAL TRADE SECRET INFORMATION owned by Quipley, Inc. and/or its affiliated companies. This information is protected by applicable state law and may be protected by the federal Economic Espionage Act OF 1996 (18 U.S.C. Sec. 1831), which provides for criminal penalties of up to 15 years in prison and/or a $5 million fine for stealing, receiving, possessing and/or duplicating any information contained herein.

**Comment by irazasyed** [comment]
I know where the problem is. Please refer the this: https://github.com/irazasyed/jwt-auth-guard/issues/5#issuecomment-175152252

**Comment by irazasyed** [comment]
That package hasn't been tagged stable yet. Hence, when people actually install it. They end up seeing such kinda errors.
