### ISSUE TITLE
Which version of tymon/jwt-auth is this package suposed to work with?

### ISSUE THREAD

**Issue by siksniraps** [irazasyed/jwt-auth-guard#12]
Which version of tymon/jwt-auth is this package suposed to work with?

With v5.6 which is on the master branch I get that 

> Class tymon.jwt does not exist

I solved that by switching to v6 on the development branch of  tymon/jwt-auth , but when I use the development branch, I now get 

> Type error: Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\Models\User given, called in C:\xampp\htdocs\projects\adance\vendor\irazasyed\jwt-auth-guard\src\JwtAuthGuard.php on line 117

**Comment by irazasyed** [comment]
Please refer this: https://github.com/irazasyed/jwt-auth-guard/issues/5#issuecomment-175152252

**Comment by Frandys** [comment]
i  am using lumen and try to get token using only Email but i am get error this one -> Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\Model\User given, called in C:\wamp\www\users-project\vendor\illuminate\support\Facades\Facade.php on line 217 and defined

i am using this code to Get token -> 
$user=User::where('email','=','abc@gmail.com')->first();

if (!$userToken=JWTAuth::fromUser($user)) {
return response()->json(['error' => 'invalid_credentials'], 401);
}

return response()->json(compact('userToken'));

Please help me how i get token using only rmail address
