### ISSUE TITLE
Lumen configuration

### ISSUE THREAD

**Issue by dave-calleja** [irazasyed/jwt-auth-guard#14]
Not clear on how to implement in Lumen. The readme seems to refer to a laravel instance from the 'Usage' section. Where can i set the Guard driver in Lumen?

**Comment by irazasyed** [comment]
You should create a folder called `config` in your project's root and then copy the [auth.php](https://github.com/laravel/lumen-framework/blob/5.2/config/auth.php) file from the `lumen-framework/config/auth.php` path to your project root `config`.

Then apply the other instructions listed.

Finally, follow the steps mentioned [here](https://github.com/irazasyed/jwt-auth-guard/issues/5#issuecomment-175152252)
