### ISSUE TITLE
I get tymon.jwt does not exist

### ISSUE THREAD

**Issue by angelmartz** [irazasyed/jwt-auth-guard#15]
Hello I get error on Laravel 5.2
ReflectionException in Container.php line 738:
Class tymon.jwt does not exist

I install and configure first tymon/jwt-auth

**Comment by VegardSkui** [comment]
I fixed this error in this pull request, #16 :smile:

**Comment by antonioreyna** [comment]
I also have this error

**Comment by VegardSkui** [comment]
I think it's caused by a recent jwt-auth update

**Comment by irazasyed** [comment]
@angelmartz @antonioreyna What version of `tymon/jwt-auth` are you using?

**Comment by irazasyed** [comment]
Please note, You need to pull the very latest dev version or `0.6.*`

**Comment by antonioreyna** [comment]
hello, i got this problem again.

**Comment by antonioreyna** [comment]
there is no 0.6.\* on jwt-auth

**Comment by irazasyed** [comment]
You need to upgrade to `1.x`.
