### ISSUE TITLE
problem with logout

### ISSUE THREAD

**Issue by antonioreyna** [irazasyed/jwt-auth-guard#19]
Hello, I am trying to logout but i think something is wrong or maybe im not understanding it well, wehn you logout it calls to invalidate on the JWTAuth library, but that library method signature is:

`public function invalidate($token = false)`

And the JWTAuthGuard calls:

```
/**
     * Invalidate current token (add it to the blacklist).
     *
     * @param  boolean $forceForever
     *
     * @return boolean
     */
    public function invalidate($forceForever = false)
    {
        return $this->requireToken()->invalidate($forceForever);
    }
```

Also:

`Method [unsetToken] does not exist.`

Which is sending a boolean instead of the token.

is that correct? am i doing something wrong?

Thanks

**Comment by irazasyed** [comment]
Fixed in last commit.
