### ISSUE TITLE
Error when using guard

### ISSUE THREAD

**Issue by nerdoza** [irazasyed/jwt-auth-guard#2]
Error message that appears when 'auth:api' or 'auth' are added as middleware: 

```
ErrorException in AuthManager.php line 246: call_user_func_array() expects parameter 1 to be a valid callback, class 'Irazasyed\JwtAuthGuard\JwtAuthGuard' does not have a method 'handle'
```

Guard for _'api'_ is set to _'jwt'_:

```
    'guards'    => [
        'web' => [
            'driver'   => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver'   => 'jwt',
            'provider' => 'users',
        ],
    ],
```

I am on the stable branch of Laravel, v5.2.10 of the framework.

I will take some time tomorrow to track down what is going on, but I am hoping that it's an error that you might have solution for already.

**Comment by irazasyed** [comment]
Not sure where the issue is, Since it seems to work fine in my end but please do the `composer update` and try again. There's a new update pushed already.

Also please note, The driver's name has been changed from `jwt` to `jwt-auth`. So make sure you update the same in your application. Refer changelog for more details.

**Comment by nerdoza** [comment]
I updated both packages (jwt-auth and jwt-auth-guard) to the dev branches and changed over driver name to `jwt-auth`.  I'm getting the same error however.  I'll keep looking into it.

**Comment by nerdoza** [comment]
Digging deeper into it, it appears that `jwt-auth` is just not setup to function as middleware.  There is no `handle` method and no authentication instances to authenticate to.  It's possible to add it in by injecting an instance of `JWTAuth` in the constructor, but considering that most of this code already exists in the jwt-auth library, I will make the PR there.

**Comment by irazasyed** [comment]
It doesn't come with a middleware but i think Lumen 5.2 already comes with one just not enabled by default. Here's the `authenticate.php` middleware i have:

``` php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Contracts\Auth\Factory as Auth;

class Authenticate
{
    /**
     * The authentication guard factory instance.
     *
     * @var \Illuminate\Contracts\Auth\Factory
     */
    protected $auth;

    /**
     * Create a new middleware instance.
     *
     * @param  \Illuminate\Contracts\Auth\Factory $auth
     *
     * @return void
     */
    public function __construct(Auth $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure                 $next
     * @param  string|null              $guard
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if ($this->auth->guard($guard)->guest()) {
            return response('Unauthorized.', 401);
        }

        return $next($request);
    }
}
```

Register in `bootstrap/app.php`:

``` php
$app->routeMiddleware([
     'auth' => App\Http\Middleware\Authenticate::class,
]);
```

P.S I've only tested this in Lumen, But i don't see a reason why it wouldn't also work in Laravel.

**Comment by nerdoza** [comment]
That's the missing piece, which I should have caught. I had disabled the `auth` middleware since I wasn't using it.

FYI: In Laravel, the middleware is registered in the `app/Http/Kernel.php` class.
