### ISSUE TITLE
Doesn't work with laravel 5.2

### ISSUE THREAD

**Issue by wemersonjanuario** [irazasyed/jwt-auth-guard#20]
I have just setup like your documentation, but it does'nt work.

I have this message

InvalidArgumentException in AuthManager.php line 97:
Auth guard driver [api] is not defined.

**Comment by wemersonjanuario** [comment]
any help?

**Comment by irazasyed** [comment]
@wemersonjanuario I'll have to debug. I'm actually quite busy with my current projects, Unable to get time. But I'll look over sometime this week. Sorry!

**Comment by wemersonjanuario** [comment]
Very nice @irazasyed. I Hope you can fix it soon. Thanks for your attention..

**Comment by wemersonjanuario** [comment]
dev-master is working fine. but "irazasyed/jwt-auth-guard": "^1.0", does not work

**Comment by irazasyed** [comment]
Thanks for the info @wemersonjanuario. I've just tagged the master branch and released `v1.0.2`. Please test now, it should work. 

I'm closing this ticket now but feel free to post or create a new one if you continue to encounter this issue or any other.

**Comment by wemersonjanuario** [comment]
sorry but still having problem with Laravel

**Comment by irazasyed** [comment]
@wemersonjanuario No worries. What is the error now?

**Comment by wemersonjanuario** [comment]
I have this error when start app Auth guard driver [api] is not defined.
This error also appears when run composer update on clear-compiled.

My laravel version is 5.2.29

**Comment by irazasyed** [comment]
Can you post your `config/auth.php` ?

**Comment by wemersonjanuario** [comment]
Here it is. Thanks for attention
[auth.zip](https://github.com/irazasyed/jwt-auth-guard/files/215107/auth.zip)

**Comment by wemersonjanuario** [comment]
I think the problem is another package I am using https://github.com/artesaos/defender. I've just removed it and works as a charm.

**Comment by irazasyed** [comment]
I see. Okay!

Your auth file seems to be fine btw.

**Comment by wemersonjanuario** [comment]
There is no method createJwt-AuthDriver defined in Illuminate\Auth\AuthManager.php

It stops on resolve method on line 97
