### ISSUE TITLE
JWT Auth now includes a Guard.

### ISSUE THREAD

**Issue by gcphost** [irazasyed/jwt-auth-guard#22]
Hi

I was having odd issues with attribute mutating that came down to `jwt-auth-guard` in some way. I switched to [jwt auths 1.0 dev guard](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTGuard.php) and all was resolved.

Just set the `driver` to `jwt` in your `config/app.php`

```
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
```

For some reason I was not able to mutate attributes with id_ or _id, $this->attributes['...']; would cause the `Fatal error: Maximum function nesting level of '256' reached, aborting!`.

**Comment by irazasyed** [comment]
Setting driver to `jwt` means switching to the guard provided by the official package. In which case, you no longer need this package.
