### ISSUE TITLE
jwt-auth and dependency injection?

### ISSUE THREAD

**Issue by belohlavek** [irazasyed/jwt-auth-guard#23]
How could I inject jwt-auth into my controller? My aim is to be able to use the package without facades.

Thanks for reading.

**Comment by AlexCW** [comment]
If you are talking about the actual jwt-auth-guard class then you just need to add Illuminate\Contracts\Auth\Guard as a namespace to the controller and inject it into the constructor. Then provided you are using the jwt-auth provider in your auth.php file you should have access to the guard. 

If you are actually talking about the original JWTAuth class then you can use the Tymon\JWTAuth\Providers\Auth\AuthInterface namespace and inject that in and it will give you access to the IlluminateAuthAdapter.

**Comment by belohlavek** [comment]
Got it working, thanks! :+1: 
Had to [solve a little CacheManager dependency error](https://github.com/tymondesigns/jwt-auth/issues/179#issuecomment-197064545) though!
