### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by cargie** [irazasyed/jwt-auth-guard#26]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**
- [ ] I have read and understood the [contributors guide](CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**
- [ ] I have never used the project.
- [*] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**My project stack details**
- Framework (Laravel / Lumen): Laravel
- Framework Version: 5.2
- JWT Auth Guard Version: 1@dev
## \- `tymon/jwt-auth` Version: 1.0.4

Type error: Argument 1 passed to Irazasyed\JwtAuthGuard\JwtAuthGuard::login() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\User given, called in /home/cargie/Projects/Php/dbventures2/vendor/irazasyed/jwt-auth-guard/src/JwtAuthGuard.php on line 114

**Comment by irazasyed** [comment]
You have not properly setup JWT-Auth. Please refer their documentation.
