### ISSUE TITLE
[BUG] Error on $token = Auth::generateTokenById(1);

### ISSUE THREAD

**Issue by jab1000** [irazasyed/jwt-auth-guard#31]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**
- [x] I have read and understood the [contributors guide](CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**
- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**My project stack details**
- Framework (Laravel / Lumen):
- Framework Version: Laravel
- JWT Auth Guard Version:  installed today -> 1.0
- `tymon/jwt-auth` Version: ^1.0@dev installed

---

Thanks for the "wrapper" -- spent too much trying to get the "guards" to work directly in the tymon project.

I am getting the following error though:

ErrorException in JWT.php line 59:
at HandleExceptions->handleError('4096', 'Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\User given, called in /Sites/tpHP/vendor/irazasyed/jwt-auth-guard/src/JwtAuthGuard.php on line 177 and defined', '/Sites/tpHP/vendor/tymon/jwt-auth/src/JWT.php', '59', array()) in JWT.php line 59

Here is the top majority of the stack trace just in case:
1.  in JWT.php line 59   
2.  at HandleExceptions->handleError('4096', 'Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\User given, called in /Sites/tpHP/vendor/irazasyed/jwt-auth-guard/src/JwtAuthGuard.php on line 177 and defined', '/Sites/tpHP/vendor/tymon/jwt-auth/src/JWT.php', '59', array()) in JWT.php line 59
3.  at JWT->fromUser(object(User)) in JwtAuthGuard.php line 177
4.  at JwtAuthGuard->generateTokenById('37')
5.  at call_user_func_array(array(object(JwtAuthGuard), 'generateTokenById'), array('37')) in AuthManager.php line 292
6.  at AuthManager->__call('generateTokenById', array('37')) in Facade.php line 217
7.  at AuthManager->generateTokenById('37') in Facade.php line 217
8.  at Facade::__callStatic('generateTokenById', array('37')) in routes.php line 47
9.  at Auth::generateTokenById('37') in routes.php line 47
10. at RouteServiceProvider->{closure}()
11. at call_user_func_array(object(Closure), array()) in Route.php line 158
12. at Route->runCallable(object(Request)) in Route.php line 137
13. at Route->run(object(Request)) in Router.php line 724
14. at Router->Illuminate\Routing{closure}(object(Request))
15. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    .....

**Comment by irazasyed** [comment]
Thanks for opening the issue. It looks like, You haven't implemented the `JWTSubject`.

Please refer this comment (The implementation example): https://github.com/irazasyed/jwt-auth-guard/issues/5#issuecomment-175152252

Once you implement that, it should work (If all the other steps are done properly).

Hope that helps. Please re-open if it doesn't work. Thanks!
