### ISSUE TITLE
[QUESTION] Rate Limiting Does Not Work

### ISSUE THREAD

**Issue by mdavis1982** [irazasyed/jwt-auth-guard#32]
**In raising this issue, I confirm the following (please check boxes):**
- [x] I have read and understood the [contributors guide](CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**
- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**My project stack details**
- Framework (Laravel / Lumen): Laravel
- Framework Version: 5.2
- JWT Auth Guard Version: ^1.0
- `tymon/jwt-auth` Version: ^1.0@dev

---

When adding the guard, the throttle options for the Laravel API middleware does not seem to work. Is there a way to get this working?

**Comment by irazasyed** [comment]
That's not implemented in this middleware. I haven't explored throttling options nor use it in my project. If you've implemented, feel free to send a PR.
