### ISSUE TITLE
jwt auth guard not working properly with Laravel 5.3 

### ISSUE THREAD

**Issue by mukeshp004** [irazasyed/jwt-auth-guard#35]
**[BUG]**
Token generated by client guard Works for the other guard too.
app cannot  distinguish  the generated token is client or employee token.

'admin' => [
    'driver' => 'jwt-auth',
    'provider' => 'admins',
],
'client' => [
    'driver' => 'jwt-auth',
    'provider' => 'clients',
],
'employee' => [
    'driver' => 'jwt-auth',
    'provider' => 'employees',
]

Route

Route::group(['prefix' => 'v1'], function () {
    Route::group(['prefix' => 'client'], function (){
        Route::any('login', 'ClientController@login');

```
    Route::group([ 'middleware' => ['auth:client']], function (){
        Route::get('detail', 'ClientController@authenticated');

        Route::resource('item', 'itemController');
    });
});

Route::group(['prefix' => 'employee'], function () {
    Route::any('login', 'EmployeeController@login');

    Route::group([ 'middleware' => ['auth:employee']], function (){
        Route::get('detail', 'EmployeeController@authenticated');

        Route::resource('item', 'itemController');
    });
});

Route::resource('user', 'UserController');
Route::resource('item', 'itemController');
```

});

jwt auth | guard doesnt  distinguish the client token or employee token.
Token generated by client guard give the access to both client and employee access

**Comment by engAhmad** [comment]
Use the tymondesigns/jwt-auth with out this repo 
[Using JWTGuard with Laravel 5.2.x](https://github.com/tymondesigns/jwt-auth/issues/513#issuecomment-186087297)

**Comment by mukeshp004** [comment]
thanks for the reply,
it worked (y).
