### ISSUE TITLE
[BUG] "Class tymon.jwt does not exist" - Laravel 5.4

### ISSUE THREAD

**Issue by iamgoodbytes** [irazasyed/jwt-auth-guard#38]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**My project stack details**

- Framework (Laravel):
- Framework Version: 5.4
- JWT Auth Guard Version: ^1.0
- `tymon/jwt-auth` Version: 0.5.*

---

Laravel 5.4 throws the error "Class tymon.jwt does not exist" after installing jwt-auth-guard and configuring it as described in the docs.

**Comment by libasoles** [comment]
Same here

> ReflectionException: Class tymon.jwt does not exist in /src/vendor/illuminate/container/Container.php:719

**Comment by libasoles** [comment]
Finally! I was outdated.

You need this version in composer.json, not 0.5!

> "tymon/jwt-auth": "^1.0@dev",

So, the Provider now is:
`$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);`

And you must publish your config/jwt.php again to avoid conflicts.
(I just copied from this gist: https://gist.github.com/jonsa/90a8bf9b4ecac7f9dd2d)

**Comment by iamgoodbytes** [comment]
Thanks @libasoles 
Got it, closed!
