### ISSUE TITLE
Possible w/o Facades?

### ISSUE THREAD

**Issue by jakecarlson** [irazasyed/jwt-auth-guard#4]
Ever considered a version that doesn't use facades so that folks with facades turned off in Lumen can use this?

**Comment by irazasyed** [comment]
I did. But i had trouble getting it working without Facade due to the dependent package (at the time when i created this driver/package). Maybe their recent changes fixes the issue i was facing. So I'll give a try again and push the changes soon.

**Comment by irazasyed** [comment]
Pushed with the changes. But the driver has now been renamed to `jwt-auth` please make sure you update the same.

The rename is because, The depended package also now supports a guard that is named as `jwt`. So to avoid conflicts, it has been renamed. Let me know if you have any Q.

**Comment by jakecarlson** [comment]
@irazasyed Wow thanks for the quick response. Unfortunately, I'm getting a fatal error after updating to the latest version:

```
Fatal error: Maximum function nesting level of '250' reached, aborting! in /home/vagrant/snabbo-api-lumen/vendor/illuminate/container/Container.php on line 700
```

I updated auth config as follows:

```
'guards' => [
        'api' => [
            'driver' => 'jwt-auth',
            'provider' => 'users'
        ],
],
```

Do I need to update anything else?

**Comment by irazasyed** [comment]
No problem!

Did you also update the [tymon/jwt-auth](https://github.com/tymondesigns/jwt-auth) package?

**Comment by jakecarlson** [comment]
I was on the latest version of 0.5.\* and tried updating to dev-master just in case ... same error. It was working with facades enabled and 'jwt' driver; I only updated the packages and changed 'jwt' driver to 'jwt-auth'.

**Comment by irazasyed** [comment]
Please use the `0.6.*@dev` version.

`"tymon/jwt-auth": "0.6.*@dev"`

It has a class that is required for this package to get everything working.

**Comment by jakecarlson** [comment]
Gotcha, thanks. Updated it but I'm unclear as to which provider to register to the app in Lumen.

```
$app->register('Tymon\JWTAuth\Providers\JWTAuthServiceProvider');
```

That no longer exists and the others I've tried don't seem to work either.

```
$app->register('Tymon\JWTAuth\Providers\LumenServiceProvider');
```

ReflectionException in Container.php line 736:
Class Tymon\JWTAuth\Providers\JWT\NamshiAdapter does not exist

Sure enough it doesn't exist -- maybe things are just too volatile in that repo ATM?

**Comment by jakecarlson** [comment]
Ah, the config changed .. working through it now.

**Comment by jakecarlson** [comment]
Got it working! Thanks so much for your patience, and for the package.

**Comment by irazasyed** [comment]
Cool. I'm glad it's working for you now. You're welcome :)
