### ISSUE TITLE
Class tymon.jwt does not exist

### ISSUE THREAD

**Issue by nerdoza** [irazasyed/jwt-auth-guard#5]
I just updated and changed my `auth.php` but am now getting a `ReflectionException`.

```
ReflectionException in Container.php line 738:
Class tymon.jwt does not exist in Container.php line 738
at ReflectionClass->__construct('tymon.jwt') in Container.php line 738
at Container->build('tymon.jwt', array()) in Container.php line 633
at Container->make('tymon.jwt', array()) in Application.php line 674
at Application->make('tymon.jwt') in Container.php line 1178
at Container->offsetGet('tymon.jwt') in JwtAuthGuardServiceProvider.php line 29
at JwtAuthGuardServiceProvider->Irazasyed\JwtAuthGuard\{closure}(object(Application), 'api', array('driver' => 'jwt-auth', 'provider' => 'users')) in AuthManager.php line 92
```

Is there an alias that is supposed to be implement or something that is missing from the docs?

**Comment by irazasyed** [comment]
What version of JWT Auth package are you using?

You're supposed to pull in the dev develop branch. That's `0.6.*@dev`.

**Comment by nerdoza** [comment]
I was on the stable branch.  I've updated to dev and am working on figuring out changes to the new provider structure.  Any hints on getting it working?

EDIT: Figured it out.  Config file changed, and changed provider to `Tymon\JWTAuth\Providers\LaravelServiceProvider::class`

**Comment by nerdoza** [comment]
Alright, I was able to get dev up and running.  For future users, here's the steps I had to take:
1. Move to dev branch on JWT Auth `1.0.*@dev`
2. Change service provider to `Tymon\JWTAuth\Providers\LaravelServiceProvider::class`
3. Update config file to https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php
4. Implement new `JWTSubject` interface on the `User` model:

```
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject as JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    protected $fillable = [
        'username',
        'password',
    ];

    protected $hidden = [
        'password',
        'created_at',
        'updated_at',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT
     *
     * @return mixed
     */
    public function getJWTIdentifier(){
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT
     *
     * @return array
     */
    public function getJWTCustomClaims(){
        return [];
    }
}
```

**Comment by irazasyed** [comment]
Thanks for posting instructions. That would be helpful for new users facing such issues :+1:

**Comment by CBox** [comment]
If I follow this steps I'm getting:
ReflectionException in Container.php line 736:
Class router does not exist

From the Service Provider:
Tymon\JWTAuth\Providers\LaravelServiceProvider::class

That's not support Lumen.

And if I comment this lines:
$this->app['router']->middleware('jwt.auth', Authenticate::class);
$this->app['router']->middleware('jwt.refresh', RefreshToken::class);
$this->app['router']->middleware('jwt.check', Check::class);

I try to use Auth::attempt and getting:
Auth not found

Thanks for your help.

**Comment by ruskiyos** [comment]
@CBox 
If you are using 'Lumen', use `Tymon\JWTAuth\Providers\LumenServiceProvider::class` instead of the Larvel one.

**Comment by mrexclamation** [comment]
Hi, can you update you instructions to use 1.0._@dev instead 0.6._@dev

**Comment by irazasyed** [comment]
@juavidn I updated.
