### ISSUE TITLE
Example app ?

### ISSUE THREAD

**Issue by jairojair** [irazasyed/jwt-auth-guard#6]
Hello, Thanks your great job.

You have any app example using tymon/jwt-auth + JWT Auth Guard? 

Thanks again :)

**Comment by irazasyed** [comment]
Hey!

I don't have any right now but it's no different. You just install both the packages, enable the `auth` middleware in lumen/laravel depending on what you use and then refer auth docs.

You just need to set the driver of one of your guard as `jwt-auth`, that's all it takes to start using the driver.

I'll see if i can setup a bootstrap. But not anytime soon though.
