### ISSUE TITLE
Composer require not working

### ISSUE THREAD

**Issue by edstevo** [irazasyed/jwt-auth-guard#7]
Hey!

I am trying to use your package, but with no luck so far:

Could not find package irazasyed/jwt-auth-guard at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

Hope you can rectify this soon,

Thanks,

Ed

**Comment by irazasyed** [comment]
Hi,

The package is not yet tagged as stable. Hence, You need to set your `minimum-stability` to `dev` in composer.json file.

**Comment by edstevo** [comment]
Aha apologies.  So you're at the contributing stage now?

**Comment by irazasyed** [comment]
No need to apologize :)

I'm still in development stage, But i think i can tag an initial version very soon.

**Comment by edstevo** [comment]
Sure thing, sounds great! I am trying to integrate it now with the stable "tymon/jwt-auth": "^0.5.6", which has a few problems.

I used "$app->make('Tymon\JWTAuth\JWTAuth')", instead of "$app['tymon.jwt']" in the Service Provider.

Great package though! I only ever needed to solve this problem today, and you've provided the solution!

Good luck

**Comment by irazasyed** [comment]
I'd suggest you start working with the `0.6.*@dev` version of the `tymon/jwt-auth` package as it has some major changes and this package is depended on a class which is available in the develop branch.
