### ISSUE TITLE
tymon.jwt does not exist

### ISSUE THREAD

**Issue by CBox** [irazasyed/jwt-auth-guard#9]
Hey,

I'm getting error when try to use:
Auth::attempt($credentials);

The error:
ReflectionException in Container.php line 736:
Class tymon.jwt does not exist

I've register the services providers:
$app->register(Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class);
$app->register(Irazasyed\JwtAuthGuard\JwtAuthGuardServiceProvider::class);

Using Lumen 5.2.

**Comment by irazasyed** [comment]
Please refer the https://github.com/irazasyed/jwt-auth-guard/issues/5#issuecomment-175152252
